id: '#/tasks/created/1.yaml'
$schema: http://json-schema.org/draft-04/schema#
definitions:
  Payload:
    type: object
    required:
      - pid
      - userPid
      - title
      - finished
    properties:
      pid:      { type: string }
      userPid:  { type: string }
      title:    { type: string }
      finished: { type: boolean }

type: object
required:
  - name
  - version
  - jsonSchemaId
  - id
  - timestamp
  - producer
  - payload
properties:
  id:           { type: string }
  timestamp:    { type: string }
  name:         { enum: [ TaskCreated ] }
  version:      { enum: [ 1 ] }
  jsonSchemaId: { enum: [ '#/tasks/created/1.yaml' ] }
  producer:     { type: string }
  payload:      { $ref: '#/definitions/Payload' }
