id: '#/tasks/created/2.yaml'
$schema: http://json-schema.org/draft-04/schema#
definitions:
  Payload:
    type: object
    required:
      - pid
      - assignedToPid
      - title
      - jiraId
      - finished
    properties:
      pid:            { type: string }
      assignedToPid:  { type: string }
      title:          { type: string }
      jiraId:         { type: integer }
      finished:       { type: boolean }

type: object
required:
  - name
  - version
  - jsonSchemaId
  - id
  - timestamp
  - producer
  - payload
properties:
  id:           { type: string }
  timestamp:    { type: string }
  name:         { enum: [ TaskCreated ] }
  version:      { enum: [ 2 ] }
  jsonSchemaId: { enum: [ '#/tasks/created/2.yaml' ] }
  producer:     { type: string }
  payload:      { $ref: '#/definitions/Payload' }
